name: Build

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          path: mod
          combine: true

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: combine

      - uses: actions/upload-artifact@v4
        with:
          name: zoinkdoink.autodeafen
          path: ${{ steps.combine.outputs.build-output }}

      - name: Attach to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.combine.outputs.build-output }}/*.geode
          generate_release_notes: true
